version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api.network
  api:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres 
    ports:
     - 5000:5000
    restart: always
    depends_on:
      - db
    networks:
      - api.network
volumes:
  db: 
networks:
  api.network: