version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgres/data
    networks:
      - api.network
  api:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres 
    ports:
     - 5000:5000
    restart: always
    depends_on:
      - db
    networks:
      - api.network
volumes:
  db: 
networks:
  api.network: