version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgres/data
    networks:
      - api.network
  api:
    build: .
    env_file:
      - .env
    ports:
     - 5000
    restart: always
    depends_on:
      - db
    deploy:
      replicas: 3
    networks:
      - api.network
  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - db
    ports:
      - 8080:80
    networks:
      - api.network
volumes:
  db: 
networks:
  api.network: